# Generated by Django 4.0.5 on 2022-07-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_v2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(related_name='actors', to='movies_v2.movie'),
        ),
    ]
